### ISSUE TITLE
No module named 'resource'

### ISSUE THREAD

**Issue by grayskripko** [sfalkner/pySMAC#20]
Windows. Installation using pip install git+https...
http://prntscr.com/dj9vee

This may help
https://github.com/prometheus/client_python/issues/27
https://github.com/prometheus/client_python/pull/28/commits/50605d3f953ec2249a6f7e9ebeb4d4db2a728eb9

**Comment by sfalkner** [comment]
Unfortunately, pysmac will not work on Windows at the moment. The mechanism that limits a functions resources is not available on this platform. Sorry.
