### ISSUE TITLE
problem with setup.py

### ISSUE THREAD

**Issue by mlindauer** [sfalkner/pySMAC#3]
Problem 1:

```
byte-compiling build/bdist.linux-x86_64/egg/pysmac/utils/state-merge.py to state-merge.pyc
  File "build/bdist.linux-x86_64/egg/pysmac/utils/state-merge.py", line 41
    if conf is not in configurations:
                    ^
SyntaxError: invalid syntax
```

Problem 2:
`Searching for pynisher>=0.1.1
Reading https://pypi.python.org/simple/pynisher/
Couldn't retrieve index page for 'pynisher'
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for pynisher>=0.1.1
error: Could not find suitable distribution for Requirement.parse('pynisher>=0.1.1')`

**Comment by mlindauer** [comment]
Update for Problem 2:

```
Processing dependencies for pysmac==0.9
Searching for pynisher
Best match: pynisher [unknown version]
Doing git clone from http://git.pynisher.org/pynisher to /tmp/easy_install-OvMJ2K/pynisher
fatal: unable to access 'http://git.pynisher.org/pynisher/': Could not resolve host: git.pynisher.org
Processing pynisher
error: Couldn't find a setup script in /tmp/easy_install-OvMJ2K/pynisher
```

**Comment by sfalkner** [comment]
Is that Problem still present? I tried to reproduce it, but it installs fine here. What's the python version? Looks like it's pretty old if it throws syntax errors. Build fine here on Python 2.7 and 3.5
